entities:
  seaf.ta.services.environment:
    title: Environment
    objects:
      environment:
        route: "/"
        title: Имя окружения
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z0-9_\\.]*$":
          $ref: "#/$defs/seaf.ta.services.base.entity"


  seaf.ta.services.stand:
    title: Techical Stand
    objects:
      stand:
        route: "/"
        title: Имя стенда внутри окружения
    schema:
      type: object
      patternProperties:
        "^[a-zA-Z0-9_\\.]*$":
          $ref: "#/$defs/seaf.ta.services.base.entity"