entities:
  seaf.ba.products:
    title: Продукты
    schema:
      type: object
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          type: object
          properties:
            title:
              title: Наименование
              type: string
            description:
              title: Описание
              type: string
            owner:
              title: Владелец продукта
              type: string
              $ref: "#/$rels/seaf.ba.parties.party"
            receives:
              title: поступает на вход
              description: Ресурс - идет на вход чему? -> Продукту
              type: array
              items:
                $ref: "#/properties/seaf.ba.resources/$resources"
            delivers:
              title: предоставляет
              description: отношение Продукт - предоставляет  что? -> Ресурс
              type: array
              items:
                $ref: "#/properties/seaf.ba.resources/$resources"
            used_in:
              title: используется в
              type: array
              items:
                $ref: "#/$rels/seaf.ba.products.product"

          required:
            - title
            - owner
    objects:
      product:
        route: "/"
        title: Продукт-услуга
        symbol: "prd"

    presentations:

      landscape_wrapper:
        title: Продуктовый ландшафт
        type: markdown
        template: templates/landscape_wrapper.md
        source: >
          (
            $domain:= $params.domain;
            
            {"count": $count($."seaf.ba.products".$keys()),
             "domain": $domain
            }

          
          )

      landscape_graph:
        title: Продуктовый ландшафт (граф)
        type: smartants
        source: >
          (

            $ctx:= $params.domain;

            $parties:= $ctx and $_essentials._jsonata_function
                ? $context_content_refined($ctx, $).observable[($.$keys() = "membersOrd" or $.$keys() = "membersCtx") and $.*.body.entity_id = "seaf.ba.parties"].*.[{$.id: $.body}]  
                : $spread($."seaf.ba.parties").[$~>|$.*|{"entity_id": "parties"}|];

            $products:= $ctx and $_essentials._jsonata_function
                ? $context_content_refined($ctx, $).observable[($.$keys() = "membersOrd" or $.$keys() = "membersCtx") and $.*.body.entity_id = "seaf.ba.products"].*.[{$.id: $.body}]  
                : $spread($."seaf.ba.products").[$~>|$.*|{"entity_id": "products"}|];

            $parties_products:= $append($parties, $products);
            
            $icons:= $."seaf.icons";
            $pre_nodes:= $parties_products.$map($, function($v) {(
                $title:= $v.*.title ? $v.*.title : "untitled";
                $size:= $length($title);
                $symbol_width:= 25 + ($size > 7 ? $size*14 : $size*16 );
                                    $symbol:= $_essentials._jsonata_function
                                      ? $getSymbol_t1($title, $v.*.entity_id, $symbol_width, $icons)
                                      : $getSymbol($title, $v.*.entity_id, $symbol_width, $icons);
                { "nodes": {
                      ($split($v.$keys(), ".")[-1] ? $split($v.$keys(), ".")[-1] : $v.$keys()): {
                          "title": $title, 
                          "symbol": $symbol.title}
                      },
                   "links": $append(
                              $v.*.owner ?
                                [
                                    { "from": ($split($v.$keys(), ".")[-1] ? $split($v.$keys(), ".")[-1] : $v.$keys()),
                                      "to": ($split($v.*.owner, ".")[-1] ? $split($v.*.owner, ".")[-1] : $v.*.owner),
                                      "title": "владелец",
                                      "style": "->"
                                    }

                                ] : [],

                              $map($v.*.has_interest, function($vv) {
                                $count($vv)>0 ?
                                  { "from": ($split($v.$keys(), ".")[-1] ? $split($v.$keys(), ".")[-1] : $v.$keys()),
                                    "to": ($split($vv.id, ".")[-1] ? $split($vv.id, ".")[-1] : $vv.id),
                                    "title": "заинтересован",
                                    "style": "-[#green]->"
                                  
                                  }
                              })
                            ),   

                  "symbols": {
                      $symbol.title: $symbol.svg}
                };
            )});

            $nodes:= $merge($pre_nodes.nodes);

            {"config": {
              "distance": 10,
              "trackWidth": 24,
              "hideLeafTitles": true
              },
             "symbols": $merge($pre_nodes.symbols), 
             "nodes": $nodes,
             "links": [$pre_nodes.links][$.from in $nodes.$keys() and $.to in $nodes.$keys()]
            } 
          )


