rules:
  validators:
    seaf.validation.ta.environments.environment_existence:
      uid: SEAF-TA-EXIST-ENVIRONMENT
      title: Проверка наличия Окружения (environment)
      description: |
        Проверяет, что в архитектуре описано хотя бы одно Окружение (seaf.ta.services.environment).
      correction: |
        Убедитесь, что в файлах архитектуры (`/architecture/ta/`) создан
        хотя бы один объект типа `seaf.ta.services.environment`.
      source: |
        ([
          $count($."seaf.ta.services.environment") = 0 ? {
              "uid": "seaf.validation.ta.existence.environment",
              "title": "Отсутствует описание Окружения (environment)",
              "correction": "Необходимо описать хотя бы одно Окружение (seaf.ta.services.environment) в архитектуре.",
              "description": "В архитектуре не описано ни одного Окружения."
          }
        ])